feat: add colours to commit hook messages

diff --git a/.githooks/commit-msg b/.githooks/commit-msg
--- a/.githooks/commit-msg
+++ b/.githooks/commit-msg
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+NO_COLOUR='\033[0m'
+
 # ---------------------------------------------------------
 # conventional commit check
 # ---------------------------------------------------------
@@ -10,8 +14,8 @@ FILE=`cat $1`
 echo "Commit Message: ${FILE}"
 
 if ! [[ $FILE =~ $REGEX ]]; then
-	echo >&2 "ERROR: Commit aborted for not following the Conventional Commit standard.​"
+	echo -e >&2 "${RED}FAIL: Commit aborted for not following the Conventional Commit standard.${NO_COLOUR}"
 	exit 1
 else
-	echo >&2 "Valid commit message."
+	echo -e >&2 "${GREEN}PASS: valid commit message${NO_COLOUR}"
 fi
